# -*- coding: utf-8 -*-
"""Code Frame.ipynb

Automatically generated by Colab.
. Use the following code in your application to request a model response
"""

import streamlit as st
from google import genai
from google.genai import types
import os

def generate():
    # Get the latest user input from Streamlit
    prompt = st.session_state.get("last_prompt", None)

    if not prompt:
        st.warning("Please enter a prompt to start the conversation.")
        return ""

    # Initialize the client for Vertex AI
    client = genai.Client(
        vertexai=True,
        project="essential-aleph-333923", #change project id
        location="global",
    )

    model = "gemini-2.5-flash-preview-09-2025"

    contents = [
        types.Content(
            role="user",
            parts=[types.Part(text=prompt)]  # ✅ Pass the user prompt here
        ),
    ]

    tools = [
        types.Tool(
            retrieval=types.Retrieval(
                vertex_ai_search=types.VertexAISearch(
                    datastore="projects/essential-aleph-333923/locations/global/collections/default_collection/dataStores/product-faq-data-id" #change datastore id and project
                )
            )
        ),
    ]

    generate_content_config = types.GenerateContentConfig(
        temperature=1,
        top_p=0.95,
        max_output_tokens=8192,
        safety_settings=[
            types.SafetySetting(category="HARM_CATEGORY_HATE_SPEECH", threshold="BLOCK_MEDIUM_AND_ABOVE"),
            types.SafetySetting(category="HARM_CATEGORY_DANGEROUS_CONTENT", threshold="BLOCK_ONLY_HIGH"),
            types.SafetySetting(category="HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold="BLOCK_MEDIUM_AND_ABOVE"),
            types.SafetySetting(category="HARM_CATEGORY_HARASSMENT", threshold="BLOCK_MEDIUM_AND_ABOVE"),
        ],
        tools=tools,
    )

    output_text = ""
    for chunk in client.models.generate_content_stream(
        model=model,
        contents=contents,
        config=generate_content_config,
    ):
        if not chunk.candidates or not chunk.candidates[0].content or not chunk.candidates[0].content.parts:
            continue
        output_text += chunk.text

    return output_text

# ---------------------------
# Streamlit UI
# ---------------------------
st.set_page_config(page_title="AI Product FAQ Sahabat Laut Lestari - your personal guide helper to know more about our product", page_icon="😇")
st.title("Your AI Guide Helper to know more about our product")

if "history" not in st.session_state:
    st.session_state.history = []

# Display past chat messages
for message in st.session_state.history:
    with st.chat_message(message["role"]):
        st.markdown(message["text"])

# Chat input box
if prompt := st.chat_input("How can I help you today?"):
    st.session_state.last_prompt = prompt  # Store input for `generate()`

    with st.chat_message("user"):
        st.markdown(prompt)
    st.session_state.history.append({"role": "user", "text": prompt})

    # Generate response using your simplified function
    response = generate()

    with st.chat_message("assistant"):
        st.markdown(response)
    st.session_state.history.append({"role": "assistant", "text": response})